---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: ''
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: ''
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
      - id: detect-private-key

  - repo: https://github.com/pappasam/toml-sort
    rev: ''
    hooks:
      - id: toml-sort
        args: [--in-place]

  - repo: https://github.com/myint/docformatter
    rev: ''
    hooks:
      - id: docformatter

  - repo: https://github.com/markdownlint/markdownlint
    rev: ''
    hooks:
      - id: markdownlint
        args: [--style, cirosantilli, --rules, '~first-header-h1,~first-line-h1,~no-trailing-punctuation']

  - repo: https://github.com/timothycrosley/isort
    rev: ''
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/psf/black
    rev: ''
    hooks:
      - id: black

  - repo: https://github.com/life4/flakehell
    rev: ''
    hooks:
      - id: flakehell
        types: [file, text]
        files: \.(ipynb|md|py|rst|yaml|yml)$
        additional_dependencies: [flake8-alfred, flake8-bandit, flake8-bugbear, flake8-builtins,
          flake8-comprehensions, flake8-docstrings, flake8-logging-format, flake8-markdown,
          flake8-pytest-style, flake8-typing-imports, flake8-use-fstring, flakehell, darglint,
          dlint, pep8-naming]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: ''
    hooks:
      - id: mypy

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: ''
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2', --colons, --width, '88']
